In [43]:
import pandas as pd

In [45]:
df = pd.read_csv("data/SMSSpamCollection", sep="\t", header=None)

In [46]:
# EDA

In [47]:
df.head()

      0                                                  1
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [48]:
# It will return the tuple with exact two elements (no. of rows, no. of column), which represent the dimensolnality of the dataframe.
df.shape

(5572, 2)

In [49]:
print(df.info())

<class 'pandas.DataFrame'>
RangeIndex: 5572 entries, 0 to 5571
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       5572 non-null   str
 1   1       5572 non-null   str
dtypes: str(2)
memory usage: 87.2 KB
None

In [50]:
print(df.sample())

        0                                                  1
4956  ham  Doing my masters. When will you buy a bb cos i...

In [51]:
df.columns = ["label", "message"]        # Rename the columns from 0,1 to label,massages

In [52]:
print(df.head())

  label                                            message
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [53]:
df.isnull().sum()

label      0
message    0
dtype: int64

In [54]:
df.duplicated().sum()

np.int64(403)

In [55]:
df[df.duplicated()]

     label                                            message
103    ham  As per your request 'Melle Melle (Oru Minnamin...
154    ham  As per your request 'Melle Melle (Oru Minnamin...
207    ham  As I entered my cabin my PA said, '' Happy B'd...
223    ham                             Sorry, I'll call later
326    ham                   No calls..messages..missed calls
...    ...                                                ...
5524  spam  You are awarded a SiPix Digital Camera! call 0...
5535   ham  I know you are thinkin malaria. But relax, chi...
5539   ham                         Just sleeping..and surfing
5553   ham                        Hahaha..use your brain dear
5558   ham                             Sorry, I'll call later

[403 rows x 2 columns]

In [ ]:
# Remove duplicates
df.drop_duplicates(inplace=True)

In [57]:
df.duplicated().sum()

np.int64(0)

In [58]:
df.shape

(5169, 2)

In [59]:
df["label"].value_counts()

label
ham     4516
spam     653
Name: count, dtype: int64

In [60]:
# TEXT PRE-PROCESSING

In [61]:
# Natural language tokenizer

In [62]:
import nltk
nltk.download("stopwords")

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\HP\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [63]:
from nltk.corpus import stopwords

stop_words = set(stopwords.words("english"))
print(stop_words)
print(list(stop_words)[:20])

{'very', "you'd", 'm', 'how', "they're", 'will', 'shan', "i'll", "it'd", 'have', "don't", 'once', 'in', 'are', 'o', 'so', 'does', "mightn't", 'aren', "isn't", "it'll", 'theirs', 'doesn', 'she', 'her', 'won', 'more', "doesn't", 'no', 'been', 'shouldn', 'of', 'ma', "she'd", 'haven', 'when', "haven't", 'our', 'mustn', 'isn', "they've", 'that', 'under', "i'd", 'don', 'herself', 'himself', 'above', 'its', 'such', 'there', 'if', 'now', "shan't", 'those', 'just', 'through', "she's", 'ours', "shouldn't", 'ain', 'having', 'themselves', 'hers', 's', "he'd", 'couldn', 're', "won't", 'doing', "hasn't", 'than', "he'll", 'i', 'down', 'we', 'ourselves', 'these', 'you', 'until', 'between', 'being', "needn't", 'do', 'to', 'was', 'against', 'them', "mustn't", 'then', 'before', 'from', "aren't", 'same', 'into', 'which', 'out', 'or', 'your', 'about', 'while', 'here', 've', 'him', 'below', 'it', 'because', "couldn't", "they'll", "you've", 'has', 'on', "we're", 'but', "wouldn't", "that'll", 'should', 'itself', 'what', "you'll", 'who', 'some', 'and', 'as', 'whom', 'at', 'd', "it's", 'where', 'hadn', 'further', "they'd", 'wouldn', 'hasn', 'yourselves', "we'd", 'all', 'nor', "he's", 'too', "we've", 'with', 'during', 'me', "should've", 'an', "didn't", "hadn't", 'am', 'myself', 'weren', 'off', 'why', 'didn', 't', 'can', 'by', 'over', 'few', "we'll", "weren't", 'y', 'll', 'yours', 'for', 'had', 'he', 'yourself', 'be', 'again', 'each', 'needn', 'own', 'the', 'up', "wasn't", "i'm", 'any', "i've", 'this', "you're", 'mightn', 'my', 'other', 'after', 'is', 'his', 'most', 'only', 'a', 'not', "she'll", 'wasn', 'both', 'did', 'they', 'their', 'were'}
['very', "you'd", 'm', 'how', "they're", 'will', 'shan', "i'll", "it'd", 'have', "don't", 'once', 'in', 'are', 'o', 'so', 'does', "mightn't", 'aren', "isn't"]

In [64]:
from nltk.stem import PorterStemmer

stemmer = PorterStemmer()

In [65]:
words = [
    "playing",
    "played",
    "plays",
    "studies",
    "studying",
    "studied",
    "connections",
    "connected",
    "connecting",
    "running",
    "run",
    "runs",
    "happiness",
    "happy",
    "happiely",
    "better"
]


for word in words:
    print(word," -> ",stemmer.stem(word))

playing  ->  play
played  ->  play
plays  ->  play
studies  ->  studi
studying  ->  studi
studied  ->  studi
connections  ->  connect
connected  ->  connect
connecting  ->  connect
running  ->  run
run  ->  run
runs  ->  run
happiness  ->  happi
happy  ->  happi
happiely  ->  happi
better  ->  better

In [66]:
from src.preprocessing import  preprocess_text

message = "CONGRATULATIONS!! You've WON a FREE Ticket!!!"

preprocess_text(message)

'congratul youv won free ticket'

In [67]:
import sklearn
from sklearn.feature_extraction.text import CountVectorizer

messages = [
    "free offer now",
    "claim free prize",
    "metting tommorow"
]

cv = CountVectorizer()

X = cv.fit_transform(messages)

print(type(X))

print(X.shape)

print(cv.vocabulary_)

print(X)

print(X.toarray())

<class 'scipy.sparse._csr.csr_matrix'>
(3, 7)
{'free': 1, 'offer': 4, 'now': 3, 'claim': 0, 'prize': 5, 'metting': 2, 'tommorow': 6}
<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 8 stored elements and shape (3, 7)>
  Coords	Values
  (0, 1)	1
  (0, 4)	1
  (0, 3)	1
  (1, 1)	1
  (1, 0)	1
  (1, 5)	1
  (2, 2)	1
  (2, 6)	1
[[0 1 0 1 1 0 0]
 [1 1 0 0 0 1 0]
 [0 0 1 0 0 0 1]]

In [68]:
print(df.columns)

Index(['label', 'message'], dtype='str')

In [69]:
# print(df.head())

In [70]:
df["target"] = df["label"].map({
    "ham":0,
    "spam":1
})

df["transformmed_text"] = df["message"].apply(preprocess_text)

In [71]:
from sklearn.model_selection import train_test_split

X = df["transformmed_text"]
y = df["target"]

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

In [72]:
cv = CountVectorizer(max_features=3000)

X_train = cv.fit_transform(X_train)

X_test = cv.transform(X_test)

In [73]:
print(X_train.shape)
print(X_test.shape)

(4135, 3000)
(1034, 3000)

In [74]:
from sklearn.naive_bayes import MultinomialNB

# Create model
model = MultinomialNB()

# Train Model
model.fit(X_train,y_train)

# Predict
y_pred = model.predict(X_test)

# View first 10 prediction
for actual, predicted in zip(y_test[:10],y_pred[:10]):
    print(f"Actual: {actual} | Predicted: {predicted}")

Actual: 0 | Predicted: 0
Actual: 0 | Predicted: 0
Actual: 0 | Predicted: 0
Actual: 0 | Predicted: 0
Actual: 0 | Predicted: 0
Actual: 0 | Predicted: 0
Actual: 0 | Predicted: 0
Actual: 0 | Predicted: 0
Actual: 0 | Predicted: 0
Actual: 0 | Predicted: 0

In [75]:
pd.reset_option("display.max_columns")
pd.reset_option("display.max_colwidth")

In [76]:
print(df.head(10))

  label                                            message  target  \
0   ham  Go until jurong point, crazy.. Available only ...       0
1   ham                      Ok lar... Joking wif u oni...       0
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...       1
3   ham  U dun say so early hor... U c already then say...       0
4   ham  Nah I don't think he goes to usf, he lives aro...       0
5  spam  FreeMsg Hey there darling it's been 3 week's n...       1
6   ham  Even my brother is not like to speak with me. ...       0
7   ham  As per your request 'Melle Melle (Oru Minnamin...       0
8  spam  WINNER!! As a valued network customer you have...       1
9  spam  Had your mobile 11 months or more? U R entitle...       1

                                   transformmed_text
0  go jurong point crazi avail bugi n great world...
1                              ok lar joke wif u oni
2  free entri 2 wkli comp win fa cup final tkt 21...
3                u dun say earli hor u c alreadi say
4          nah dont think goe usf live around though
5  freemsg hey darl 3 week word back id like fun ...
6      even brother like speak treat like aid patent
7  per request mell mell oru minnaminungint nurun...
8  winner valu network custom select receivea £90...
9  mobil 11 month u r entitl updat latest colour ...

In [77]:
# MODEL EVALUATION

In [78]:
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix,
    classification_report
)

print("Accuracy: ",accuracy_score(y_test,y_pred))
print("Precision: ",precision_score(y_test,y_pred))
print("Recall: ",recall_score(y_test,y_pred))
print("F1 Score: ", f1_score(y_test,y_pred))
print("\n",classification_report(y_test,y_pred))
print("\nConfusion matrix:")
print(confusion_matrix(y_test,y_pred))

Accuracy:  0.9787234042553191
Precision:  0.936
Recall:  0.8931297709923665
F1 Score:  0.9140625

               precision    recall  f1-score   support

           0       0.98      0.99      0.99       903
           1       0.94      0.89      0.91       131

    accuracy                           0.98      1034
   macro avg       0.96      0.94      0.95      1034
weighted avg       0.98      0.98      0.98      1034


Confusion matrix:
[[895   8]
 [ 14 117]]

In [79]:
# from sklearn.model_selection import train_test_split

# X = df["transformmed_text"]
# y = df["target"]

# X_train_text, X_test_text, y_train, y_test = train_test_split(
#     X,
#     y,
#     test_size=0.2,
#     random_state=42,
#     stratify=y
# )

In [80]:
# from sklearn.feature_extraction.text import  TfidfVectorizer

# # create TF-IDF vectorizer
# tfidf = TfidfVectorizer()



# # Learn vocabulary from training data
# X_train_tfidf = tfidf.fit_transform(X_train_text)

# # Transfrom test data
# X_test_tfidf = tfidf.transform(X_test_text)

# # Trian model
# model_tfidf = MultinomialNB()
# model_tfidf.fit(X_train_tfidf,y_train)

# # Predict
# y_pred_tfidf = model_tfidf.predict(X_test_tfidf)

In [81]:
# from sklearn.metrics import (
#     accuracy_score,
#     precision_score,
#     recall_score,
#     f1_score,
#     confusion_matrix,
#     classification_report
# )

# print("Accuracy: ",accuracy_score(y_test,y_pred_tfidf))
# print("Precision: ",precision_score(y_test,y_pred_tfidf))
# print("Recall: ",recall_score(y_test,y_pred_tfidf))
# print("F1 Score: ", f1_score(y_test,y_pred_tfidf))
# print("\n",classification_report(y_test,y_pred_tfidf))
# print("\nConfusion matrix:")
# print(confusion_matrix(y_test,y_pred_tfidf))

In [82]:
import pickle

print(os.getcwd())

with open("model/vectorizer.pkl","wb") as file:
    pickle.dump(cv, file)

with open("model/spam_model.pkl","wb") as file:
    pickle.dump(model, file) 

print("Model and vectorizer saved successfully!")

d:\Python Programs\PROJECTS\SpamDetectionNaiveBayes
Model and vectorizer saved successfully!

In [83]:
# TEST MODEL

with open("model/vectorizer.pkl","rb") as file:
    loaded_cv = pickle.load(file)

with open("model/spam_model.pkl","rb") as file:
    loaded_model = pickle.load(file)

In [84]:
msg = "Congratulation! you have won a free ticket."

msg = preprocess_text(msg)

msg = loaded_cv.transform([msg])

prediction = loaded_model.predict(msg)

print(prediction)

if prediction[0] == 1:
    print("SPAM")
else:
    print("HAM")

[1]
SPAM

In [85]:
from src.predict import predict_spam
print(os.getcwd())
# D:\Python Programs\PROJECTS\SpamDetectionNaiveBayes\src
print(predict_spam("Congratulation! you won 5000$."))
print(predict_spam("Hello! how are you??"))
print(predict_spam("Jai shree ram."))
print(predict_spam("Free entry in weekly competition!"))
print(predict_spam("Your account credited 100$."))

d:\Python Programs\PROJECTS\SpamDetectionNaiveBayes
('SPAM', np.float64(99.99))
('HAM', np.float64(96.11))
('HAM', np.float64(86.58))
('SPAM', np.float64(99.99))
('SPAM', np.float64(99.12))